language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

cache:
    directories:
        - ~/.composer/cache/files

sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction --no-scripts --prefer-dist
